[package]
name = "lightning-pool"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
affair.workspace = true
async-trait.workspace = true
bincode.workspace = true
bytes.workspace = true
dashmap = "5.5"
infusion.workspace = true
quinn.workspace = true
fleek-crypto = { path = "../../lib/fleek-crypto" }
lightning-interfaces = { path = "../interfaces" }
multiaddr = "0.17.1"
tokio.workspace = true
tokio-util.workspace = true
futures-util.workspace = true
rustls = { version = "0.21", default-features = false, features = ["dangerous_configuration"] }
rcgen = "0.11.1"
serde.workspace = true
tracing = "0.1"
