[package]
name = "lightning-pool"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes.workspace = true
infusion.workspace = true
serde.workspace = true
anyhow.workspace = true
tokio.workspace = true
async-trait.workspace = true
log.workspace = true
fleek-crypto.workspace = true
futures.workspace = true
tokio-util = { workspace = true, features = ["codec"] }
lightning-interfaces = {path="../interfaces"}
bincode.workspace = true

affair = "0.1.2"
der = { version = "0.7", features = ["alloc", "derive"] }
fleek-blake3 = "1.4"
ring = "0.16.20"
rustls = { version = "0.21", default-features = false, features = ["dangerous_configuration"] }
rcgen = "0.11.1"
quinn = "0.10"
thiserror = "1.0"
tracing = "0.1"
webpki = { version = "0.22", features = ["std"] }
x509-parser = "0.15.1"

[dev-dependencies]
lightning-application = { path="../application", features = ["test"] }
lightning-signer = { path="../signer" }
lightning-test-utils = { path = "../test-utils" }
infusion.workspace = true
