[package]
name = "lightning-pool"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
affair.workspace = true
async-trait.workspace = true
bincode.workspace = true
bytes.workspace = true
dashmap = "5.5"
der = { version = "0.7", features = ["alloc", "derive"] }
fleek-blake3 = "1.3.3"
fleek-crypto = { path = "../../lib/fleek-crypto" }
infusion.workspace = true
quinn.workspace = true
lightning-interfaces = { path = "../interfaces" }
multiaddr = "0.17.1"
tokio.workspace = true
tokio-util = {workspace = true, features = ["codec"]}
futures-util.workspace = true
thiserror.workspace = true
ring = "0.16.20"
rustls = { version = "0.21", default-features = false, features = ["dangerous_configuration"] }
rcgen = "0.11.1"
serde.workspace = true
tracing = "0.1"
webpki = { version = "0.22", features = ["std"] }
x509-parser = "0.15.1"

