[BLANK]

[application]
db_path = "~/.lightning/data/app_db"
mode = "Dev"
storage = "RocksDb"
testnet = false

[handshake]

[[handshake.worker]]
type = "AsyncWorker"

[[handshake.worker]]
type = "AsyncWorker"

[[handshake.worker]]
type = "AsyncWorker"

[[handshake.worker]]
type = "AsyncWorker"

[[handshake.transport]]
type = "WebRTC"
signal_address = "0.0.0.0:4210"

[service-executor]
services = [0]

[signer]
consensus_key_path = "~/.lightning/keystore/consensus.pem"
node_key_path = "~/.lightning/keystore/node.pem"

