[package]
name = "lightning-reputation"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = {path="../interfaces"}
fleek-crypto.workspace = true
hp-fixed.workspace = true
workspace-hack = { version = "0.1", path = "../../etc/workspace-hack" }

[dev-dependencies]
lightning-test-utils = {path="../test-utils"}
rand.workspace = true

