[workspace]
members = ["core/*", "lib/*", "services/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.5.1"
async-trait = "0.1"
tokio = { version = "1.28", features = ["full"] }
tokio-stream = "0.1"
bytes = "1.4"
thiserror = "1.0"
zeroize = "1.6"

# Our libraries
affair = { path = "lib/affair" }
atomo = { path = "lib/atomo" }
fleek-crypto = { path = "lib/fleek-crypto" }

[profile.release]
# 2 full, 0 nothing, 1 good enough.
debug = 1
# currently enabled, may increase build time, but runtime faster, can set to `"thin"`.
lto = true
# optimize for binary size, but also turn off loop vectorization.
opt-level = 'z'
# speeds up build time to offset some of the link time optimization.
codegen-units = 1
# strip debug info from binary.
strip = 'debuginfo'
# On panic terminate the process.
panic = 'abort'
