[application]
mode = "Dev"

[blockstore]

[consensus]
address = "/ip4/0.0.0.0/udp/8000"
mempool_address = "/ip4/0.0.0.0/udp/8002"
store_path = "~/.fleek/data/narwhal_store"
worker_address = "/ip4/0.0.0.0/udp/8001"

[handshake]
listen_addr = "0.0.0.0:6969"

[pod]

[rep-collector]
reporter_buffer_size = 50

[rpc]
addr = "127.0.0.1"
port = 4069

[signer]
network_key_path = "~/.lightning/keystore/network.pem"
node_key_path = "~/.lightning/keystore/node.pem"
