[package]
name = "lightning-pinger"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = { path = "../interfaces" }
lightning-utils = { path = "../utils" }
lightning-metrics = { path = "../metrics" }
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
humantime-serde.workspace = true
rand.workspace = true
tracing.workspace = true
fleek-crypto.workspace = true
workspace-hack = { version = "0.1", path = "../../etc/workspace-hack" }

[dev-dependencies]
lightning-test-utils = { path = "../test-utils" }
lightning-signer = { path = "../signer" }
lightning-application = { path = "../application", features = ["test"] }
lightning-notifier = { path = "../notifier" }
lightning-rep-collector = { path = "../rep-collector" }
