[package]
name = "fleek-cdn"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
serde.workspace = true
arrayref = "0.3"
arrayvec = "0.7"
async-trait = "0.1"
bytes = "1.4"
tokio.workspace = true
futures = "0.3"

fleek-crypto = { path = "../../lib/fleek-crypto" }
blake3-tree = { path = "../../lib/blake3-tree" }
draco-interfaces = { path="../../core/interfaces" }
draco-handshake = { path = "../../core/handshake" }
draco-sdk = {path="../../core/sdk"}

# dummy dependencies (needed to share with example)
affair = { workspace = true, optional = true }
draco-application = { path = "../../core/application", optional = true }
draco-blockstore = { path = "../../core/blockstore", optional = true }
draco-rep-collector = { path = "../../core/rep-collector", optional = true }
draco-notifier = { path = "../../core/notifier", optional = true }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports", "async_tokio"] }
affair.workspace = true
draco-application = { path = "../../core/application" }
draco-blockstore = { path = "../../core/blockstore" }
draco-rep-collector = { path = "../../core/rep-collector" }
draco-notifier = { path = "../../core/notifier" }

[features]
dummy = ["affair", "draco-application", "draco-blockstore", "draco-rep-collector", "draco-notifier"]

[[example]]
name = "cdn_server"
path = "examples/server.rs"
required-features = ["dummy"]
