[package]
name = "fleek-cdn"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
serde.workspace = true
arrayref = "0.3"
arrayvec = "0.7"
async-trait = "0.1"
bytes = "1.4"
tokio.workspace = true
futures = "0.3"

fleek-crypto = { path = "../../lib/fleek-crypto" }
blake3-tree = { path = "../../lib/blake3-tree" }
lightning-interfaces = { path="../../core/interfaces" }
lightning-handshake = { path = "../../core/handshake" }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports", "async_tokio"] }
lightning-test-utils = { path = "../../core/test-utils" }
rand = "0.8.5"

[[example]]
name = "cdn_server"
path = "examples/server.rs"

[[example]]
name = "cdn_client"
path = "examples/client.rs"
