[package]
name = "lightning-e2e"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = { path = "../interfaces", features = ["e2e-test"] }
lightning-node = { path = "../node" }
lightning-rpc = { path = "../rpc", features = ["e2e-test"] }
lightning-application = { path = "../application" }
lightning-consensus = { path = "../consensus" }
lightning-notifier = { path = "../notifier" }
lightning-handshake = { path = "../handshake" }
lightning-topology = { path = "../topology" }
lightning-signer = { path = "../signer" }
lightning-dht = { path = "../dht" }
lightning-pool = { path = "../pool" }
mock = { path = "../mock" }
infusion.workspace = true
tokio.workspace = true
anyhow.workspace = true
futures.workspace = true
serde_json.workspace = true
fleek-crypto.workspace = true
resolved-pathbuf.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde.workspace = true
rand.workspace = true
hp-fixed.workspace = true
env_logger = "0.10.0"
serial_test = "2.0.0"

toml = "0.7"
resolve-path = "0.1.0"
clap = { version = "4.2", features = ["derive"] }
