[package]
name = "lightning-e2e"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = { path = "../interfaces" }
lightning-node = { path = "../node" }
lightning-rpc = { path = "../rpc" }
lightning-application = { path = "../application" }
lightning-consensus = { path = "../consensus" }
lightning-notifier = { path = "../notifier" }
lightning-handshake = { path = "../handshake" }
lightning-topology = { path = "../topology" }
lightning-signer = { path = "../signer" }
mock = { path = "../mock" }
tokio.workspace = true
anyhow.workspace = true
futures.workspace = true
serde_json.workspace = true
fleek-crypto.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde.workspace = true

toml = "0.7"
resolve-path = "0.1.0"
