[package]
name = "lightning-handshake"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
serde.workspace = true
arrayref = "0.3"
arrayvec = "0.7"
async-trait = "0.1"
bytes = "1.4"
tokio.workspace = true
futures = "0.3"
infusion.workspace = true

fleek-crypto = { path = "../../lib/fleek-crypto" }

# Server
lightning-interfaces = { path = "../interfaces", optional = true }
dashmap = { version = "5.4", optional = true }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports", "async_tokio"] }
affair.workspace = true

[features]
default = ["server", "client"]
server = ["lightning-interfaces", "dashmap"]
client = []

[[bench]]
name = "connection"
harness = false

