[package]
name = "lightning-handshake"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log.workspace = true
anyhow.workspace = true
serde.workspace = true
infusion.workspace = true
fleek-crypto.workspace = true
async-trait.workspace = true
futures.workspace = true
tokio.workspace = true
bytes = "1.4"
arrayref = "0.3"
arrayvec = "0.7"

# Server
lightning-interfaces = { path = "../interfaces" }
dashmap = { version = "5.4", optional = true }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports", "async_tokio"] }
affair.workspace = true
