[package]
name = "draco-handshake"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
serde.workspace = true
arrayref = "0.3"
arrayvec = "0.7"
async-trait = "0.1"
bytes = "1.4"
tokio.workspace = true
futures = "0.3"

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports", "async_tokio"] }

[features]
default = ["server", "client"]
server = []
client = []

[[bench]]
name = "connection"
harness = false

