[package]
name = "draco-rpc"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
draco-interfaces = {path="../interfaces"}
axum.workspace = true
anyhow.workspace = true
jsonrpc-v2.workspace = true
serde.workspace = true
async-trait.workspace = true
serde_json.workspace = true
bincode.workspace = true
num-bigint =  { workspace = true, features = ["serde"] }

affair.workspace = true
fleek-crypto.workspace = true

[dev-dependencies]
tokio.workspace = true
reqwest = {workspace = true, features = ["json"]}
draco-application = {path="../application"}
#draco-consensus = {path="../consensus"}