[package]
name = "freek-rpc"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freek-interfaces = { path = "../interfaces" }
axum.workspace = true
anyhow.workspace = true
jsonrpc-v2.workspace = true
serde.workspace = true
async-trait.workspace = true
serde_json.workspace = true
bincode.workspace = true
tokio.workspace = true

affair.workspace = true
fleek-crypto.workspace = true
hp-fixed.workspace = true

[dev-dependencies]
reqwest = { workspace = true, features = ["json"] }
freek-application = { path = "../application" }
#freek-consensus = {path="../consensus"}
