[package]
name = "lightning-rpc"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = { path = "../interfaces" }
axum.workspace = true
anyhow.workspace = true
jsonrpc-v2.workspace = true
serde.workspace = true
async-trait.workspace = true
serde_json.workspace = true
bincode.workspace = true
tokio.workspace = true
infusion.workspace = true
autometrics.workspace = true
log.workspace = true

affair.workspace = true
fleek-crypto.workspace = true
hp-fixed.workspace = true

[dev-dependencies]
reqwest = { workspace = true, features = ["json"] }
lightning-application = { path = "../application" }
#lightning-consensus = {path="../consensus"}

[features]
e2e-test = []
