[package]
name = "example-image-classification"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
image = "0.24"
rmp-serde = "1.1"
ndarray = "0.15"
ndarray-npy = "0.8"
npyz = "0.8"
raqote = { version = "0.8", default-features = false }
reqwest = "0.11"
tokio.workspace = true
common = { path = "../common" }

