[package]
name = "lightning-tui"
version = "0.0.0"
edition = "2021"
description = "TUI for the lightning node"
authors = ["M. Meier <miguel@fleek.xyz>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
config = "0.14"
crossterm = { version = "0.27", features = ["serde", "event-stream"] }
derive_deref = "1.1"
directories = "5.0"
lightning-guard = { path = "../ebpf-apps/guard", default-features = false, features = [
    "client",
] }
futures = "0.3"
indexmap = { version = "2.2", features = ["serde"] }
indoc = "2.0"
ipnet = "2.9"
json5 = "0.4"
lazy_static = "1.4"
log = "0.4"
ratatui = { version = "0.26", features = ["serde", "macros"] }
resolved-pathbuf = { path = "../../lib/resolved-pathbuf" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.3"
socket-logger = { path = "../socket-logger", optional = true }
strum = { version = "0.26", features = ["derive"] }
tokio = { version = "1.32", features = ["full"] }
tokio-util = "0.7"
tui-logger = { version = "0.11", optional = true }
tui-textarea = "0.4"
unicode-width = "0.1"
lightning-utils = { path = "../../core/utils" }

[dev-dependencies]
pretty_assertions = "1.4"

[features]
default = []
logger = ["tui-logger", "socket-logger"]
