[package]
name = "lightning-archive"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
affair.workspace = true
anyhow.workspace = true
async-trait.workspace = true
resolved-pathbuf.workspace = true
serde.workspace = true

lightning-interfaces = { path = "../interfaces" }
