# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno_telemetry"
version = "0.11.0"
readme = "README.md"
description = "Telemetry for Deno"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
async-trait = "0.1.86"
deno_core = "0.331"
deno_error = "0.5.5"
deno_tls = "0.174"
http-body-util = "0.1.2"
hyper = { version = "1.6.0", features = ["full"] }
hyper-rustls = { version = "0.27.2", default-features = false, features = ["http1", "http2", "tls12", "ring"] }
hyper-util = { version = "0.1.10", features = ["tokio", "client", "client-legacy", "server", "server-auto"] }
log = "0.4"
once_cell = "1.20"
opentelemetry = "0.27.0"
opentelemetry-http = "0.27.0"
opentelemetry-otlp = { version = "0.27.0", features = ["logs", "http-proto", "http-json"] }
opentelemetry-semantic-conventions = { version = "0.27.0", features = ["semconv_experimental"] }
opentelemetry_sdk = "0.27.0"
pin-project = "1.0.11" # don't pin because they yank crates from cargo
serde = { version = "1.0.149", features = ["derive"] }
thiserror = "2.0.3"
tokio = { version = "1.36.0", features = ["full"] }
