[package]
name = "lightning-cli"
version = "0.1.0"
edition = "2021"
default-run = "lightning-node"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = { path = "../interfaces" }
lightning-node = { path = "../node" }
lightning-types = { path = "../types" }
lightning-utils = { path = "../utils" }

# TODO: cli ideally shouldn't depend on these directly
lightning-application = { path = "../application" }
lightning-rpc = { path = "../rpc" }
lightning-signer = { path = "../signer" }

mock = { path = "../mock" }
fleek-crypto.workspace = true
resolved-pathbuf.workspace = true
infusion.workspace = true
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
clap = { version = "4.4.2", features = ["derive"] }
tracing.workspace = true
tracing-subscriber = "0.3"
console-subscriber = { version = "0.2.0" }
fleek-blake3 = "1.5"
serde_json.workspace = true
reqwest = { workspace = true, features = ["json"] }
rand.workspace = true
human-panic = "1.2.2"
compile-time-run = "0.2.12"

[[bin]]
name = "lightning-node"
path = "src/main.rs"
