[package]
name = "lightning-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
clap = { version = "4.4.2", features = ["derive"] }
anyhow.workspace = true
resolved-pathbuf.workspace = true
log4rs = { version = "1.2.0", features = [
  "rolling_file_appender",
  "compound_policy",
  "size_trigger",
  "fixed_window_roller",
  "gzip",
] }
log.workspace = true
