[package]
name = "lightning-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = { path = "../interfaces" }
lightning-application = { path = "../application" }
lightning-broadcast = { path = "../broadcast" }
lightning-blockstore = { path = "../blockstore" }
lightning-blockstore-server = { path = "../blockstore-server" }
lightning-consensus = { path = "../consensus" }
lightning-dht = { path = "../dht" }
lightning-fetcher = { path = "../fetcher" }
lightning-handshake = { path = "../handshake" }
lightning-notifier = { path = "../notifier" }
lightning-origin-ipfs = { path = "../origin-ipfs" }
lightning-rep-collector = { path = "../rep-collector" }
lightning-resolver = { path = "../resolver" }
lightning-rpc = { path = "../rpc" }
lightning-service-executor = { path = "../service-executor" }
lightning-signer = { path = "../signer" }
lightning-topology = { path = "../topology" }
lightning-types = { path = "../types" }
mock = { path = "../mock" }
tokio.workspace = true
clap = { version = "4.4.2", features = ["derive"] }
anyhow.workspace = true
resolved-pathbuf.workspace = true
log4rs = { version = "1.2.0", features = [
  "rolling_file_appender",
  "compound_policy",
  "size_trigger",
  "fixed_window_roller",
  "gzip",
] }
log.workspace = true
toml = "0.7"
infusion.workspace = true
fleek-crypto.workspace = true
tracing = "0.1"
serde.workspace = true
atomo-rocks.workspace = true
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
