[package]
name = "draco-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
draco-application = { path = "../application" }
draco-handshake = { path = "../handshake" }
draco-interfaces = { path = "../interfaces" }
draco-rep-collector = { path = "../rep-collector" }
anyhow.workspace = true
serde.workspace = true
toml = "0.7"
async-trait.workspace = true
mockall = "0.11.4"
tokio.workspace = true
bytes.workspace = true
tokio-stream.workspace = true
fleek-crypto.workspace = true
