[package]
name = "draco-node"
version = "0.1.0"
edition = "2021"
default-run = "draco-node"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
draco-application = { path = "../application" }
draco-blockstore = { path = "../blockstore" }
draco-handshake = { path = "../handshake" }
draco-interfaces = { path = "../interfaces" }
draco-rep-collector = { path = "../rep-collector" }
draco-consensus = { path = "../consensus" }
draco-notifier = { path = "../notifier" }
draco-rpc = { path = "../rpc" }
draco-signer = { path = "../signer" }
draco-test-utils = { path = "../test-utils" }
mock = { path = "../mock" }
anyhow.workspace = true
clap = { version = "4.2", features = ["derive"] }
serde.workspace = true
toml = "0.7"
async-trait.workspace = true
mockall = "0.11.4"
tokio.workspace = true
bytes.workspace = true
tokio-stream.workspace = true
fleek-crypto.workspace = true
tracing = "0.1"
affair.workspace = true
log.workspace = true
simplelog = "0.12.1"
chrono = "0.4.26"
