[application]
mode = "Dev"

[blockstore]

[consensus]
host = "0.0.0.0"
mempool_success_rate = 0.85
port = 2120

[handshake]
listen_addr = "0.0.0.0:6969"

[indexer]

[pod]

[rep-collector]
reporter_buffer_size = 50

[rpc]
addr = "127.0.0.1"
port = 4069

[signer]
network_key_path = "~/.draco/keystore/network.pem"
node_key_path = "~/.draco/keystore/node.pem"
