[BLANK]

[application]
mode = "Dev"

[blockstore]

[broadcast]
time_to_idle_mins = 5
time_to_live_mins = 60

[connection-pool]

[consensus]
host = "0.0.0.0"
mempool_success_rate = 0.85
port = 2120

[dht]
address = "0.0.0.0:0"
bootstrappers = []

[handshake]
listen_addr = "0.0.0.0:6969"

[rep-collector]
reporter_buffer_size = 50

[rpc]
addr = "127.0.0.1"
port = 4069

[signer]
consensus_key_path = "~/.lightning/keystore/consensus.pem"
node_key_path = "~/.lightning/keystore/node.pem"

[topology]
testing_min_nodes = 9
testing_target_k = 8
