[package]
name = "draco-rep-collector"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
draco-interfaces = {path="../interfaces"}
draco-application = {path="../application/"}
anyhow.workspace = true
serde.workspace = true
async-trait.workspace = true
fleek-crypto.workspace = true
tokio.workspace = true
lru.workspace = true
