[package]
name = "fleek-service-ml"
version = "0.0.0"
edition.workspace = true

[dependencies]
bytes.workspace = true
fn-sdk = { path = "../../lib/sdk" }
serde.workspace = true
serde_json.workspace = true
tch = { version = "0.15", features = ["download-libtorch"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
tokio.workspace = true

[[bin]]
name = "fn-service-3"
path = "src/bin.rs"
