[package]
name = "example-image-classification"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
base64 = "0.21"
bincode.workspace = true
image = "0.24"
ndarray = "0.15"
ndarray-npy = "0.8"
npyz = "0.8"
raqote = { version = "0.8", default-features = false }
reqwest = "0.11"
serde_json.workspace = true
tokio.workspace = true
common = { path = "../common" }

