[package]
name = "example-image-classification"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
base64 = "0.21"
image = "0.24"
ndarray = "0.15"
ndarray-npy = "0.8"
npyz = "0.8"
raqote = { version = "0.8", default-features = false }
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tch = { version = "0.15", features = [ "download-libtorch" ] }
tokio = { version = "1.32", features = ["macros"] }

