[package]
name = "draco-application"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
draco-interfaces = { path = "../interfaces" }

# Our libraries
affair.workspace = true
atomo.workspace = true
