[package]
name = "service-executor"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = { path = "../interfaces/" }
fn-sdk = { path = "../../lib/sdk" }
tokio.workspace = true
async-channel = "1.9.0"

# Built-in services
fleek-service-ping-example = { path = "../../services/ping" }
