[package]
name = "service-executor"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = { path = "../interfaces/" }

# Built-in services
fleek-service-ping-example = { path = "../../services/ping" }
