[package]
name = "lightning-service-executor"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = { path = "../interfaces/" }
fn-sdk = { path = "../../lib/sdk" }
tokio.workspace = true
async-trait.workspace = true
anyhow.workspace = true
serde.workspace = true
tracing.workspace = true
async-channel = "1.9.0"
triomphe = "0.1.9"
dashmap = "5.5"
fxhash = "0.2"
resolved-pathbuf.workspace = true

# Built-in services
fleek-service-ping-example = { path = "../../services/ping" }
fleek-service-big-buck-bunny = { path = "../../services/big-buck-bunny" }
