[package]
name = "freek-signer"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freek-interfaces = { path = "../interfaces" }
freek-application = { path = "../application" }
anyhow.workspace = true
async-trait.workspace = true
log.workspace = true
serde.workspace = true
tokio.workspace = true
dirs.workspace = true

fleek-crypto.workspace = true
affair.workspace = true

[dev-dependencies]
freek-test-utils = { path = "../test-utils" }
hp-fixed.workspace = true
