[package]
name = "draco-signer"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
draco-interfaces = {path="../interfaces"}
draco-application = {path="../application"}
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
tokio.workspace = true
dirs.workspace = true

fleek-crypto.workspace = true
affair.workspace = true

[dev-dependencies]
draco-test-utils = {path="../test-utils"}
hp-float.workspace = true
