[package]
name = "fleek-service-js-poc"
version = "0.0.1"
edition.workspace = true

[dependencies]
anyhow.workspace = true
arrayref = "0.3"
blake3-tree = { path = "../../lib/blake3-tree" }
bytes.workspace = true
cid = "0.11"
fleek-crypto.workspace = true
fn-sdk = { path = "../../lib/sdk" }
hex = "0.4"
lightning-schema = { path = "../../core/schema" }
lightning-workspace-hack.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util = { version = "0.7", features = ["rt"] }
tracing.workspace = true
triomphe = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
urlencoding = "2.1"
num_cpus = "1.16"

# Deno core + webapi extensions
deno_canvas = "0.56.0"
deno_crypto = "0.201.0"
deno_console = "0.187.0"
deno_core = "0.331.0"
deno_fetch = "0.211.0"
deno_fleek = { path = "deno_fleek" }
deno_fs = "0.97.0"
deno_io = "0.97.0"
deno_net = "0.179.0"
deno_node = "0.125.0"
deno_web = "0.218.0"
deno_url = "0.187.0"
deno_webgpu = "0.154.0"
deno_webidl = "0.187.0"
deno_websocket = "0.192.0"

[build-dependencies]
deno_canvas = "0.56.0"
deno_crypto = "0.201.0"
deno_console = "0.187.0"
deno_core = "0.331.0"
deno_fetch = "0.211.0"
deno_fleek = { path = "deno_fleek" }
deno_fs = "0.97.0"
deno_io = "0.97.0"
deno_net = "0.179.0"
deno_node = "0.125.0"
deno_web = "0.218.0"
deno_url = "0.187.0"
deno_webgpu = "0.154.0"
deno_webidl = "0.187.0"
deno_websocket = "0.192.0"

[[bin]]
name = "fn-service-1"
path = "src/bin.rs"
