[package]
name = "lightning-table"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow.workspace = true
bincode.workspace = true
lightning-interfaces = { path="../interfaces" }
fleek-crypto.workspace = true
futures.workspace = true
serde.workspace = true
rand.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing = "0.1"
