[package]
name = "draco-table"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow.workspace = true
bincode.workspace = true
draco-interfaces = { path="../interfaces" }
fleek-crypto.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
