[package]
name = "draco-blockstore"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
draco-interfaces = { path="../interfaces" }
blake3-tree = { path = "../../lib/blake3-tree"}
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
parking_lot.workspace = true
serde.workspace = true
