[package]
name = "interfaces"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
serde = "1.0"
async-trait = "0.1"
tokio = {version="1.28", features=["full"]}
tokio-stream = "0.1"
bytes = "1.4"
