[package]
name = "draco-application"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bincode.workspace = true
serde.workspace = true
toml = "0.7.4"
multiaddr = "0.17.1"
draco-interfaces = { path = "../interfaces" }
draco-reputation = { path = "../reputation" }
num-traits.workspace = true
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "c961a01596a87e76f590c7e43aca9d57106dbbb1" }

# Our libraries
affair.workspace = true
atomo.workspace = true
fleek-crypto.workspace = true
big-decimal.workspace = true


[dev-dependencies]
draco-test-utils = {path="../test-utils"}
tokio.workspace = true
rand.workspace = true
