[package]
name = "freek-application"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bincode.workspace = true
lazy_static.workspace = true
serde.workspace = true
toml = "0.7.4"
multiaddr = "0.17.1"
freek-interfaces = { path = "../interfaces" }
freek-reputation = { path = "../reputation" }
num-traits.workspace = true

# Our libraries
affair.workspace = true
atomo.workspace = true
fleek-crypto.workspace = true
hp-fixed.workspace = true


[dev-dependencies]
freek-test-utils = { path = "../test-utils" }
tokio.workspace = true
rand.workspace = true

[features]
test = []
