epoch_start = 1684276288383
epoch_time = 120000
committee_size = 10
min_stake = 1000
eligibility_time = 1
lock_time = 5
protocol_share = 0
node_share = 80
service_builder_share = 20
max_inflation = 10
consumer_rebate = 0
max_boost = 4
max_lock_time = 1460                                                   # 1460 days(epoch) meaning 4 years
supply_at_genesis = 1000000                                            # set to 1 million for testing, to be determined when initial allocations are set
protocol_fund_address = "Agio046PQ/xQ3UnqxlhSaoHVtJTWXegU/TdpLwnEMIFW"

[[committee]]
owner = "Atw4vg1vuqs1yFA+POhP2IM8H+f+bHkxq2Y4pBhUQfbP"
primary_public_key = "l0Jel6KEFG7H6sV2nWKOQxDaMKWMeiUBqK5VHKcStWrLPHAANRB+dt7gp0jQ7ooxEaI7ukOQZk6U5vcL7ESHA1J/iAWQ7YNO/ZCvR1pfWfcTNBONIzeiUWAN+iyKfV10"
primary_address = "/ip4/127.0.0.1/udp/18000"
network_key = "0UQnMH+oHTzvNCw+TGhXLgIo1uim+JDiTvQxdGqAu/A="
worker_address = "/ip4/127.0.0.1/udp/18101/http"
worker_public_key = "0UQnMH+oHTzvNCw+TGhXLgIo1uim+JDiTvQxdGqAu/A="
worker_mempool = "/ip4/127.0.0.1/tcp/18102/http"

[[committee]]
owner = "ArKFx+pWTH8KKWHT/y9fCUMjddQ1aXpRDFYD2ZYc42vd"
primary_public_key = "qipezx5pzmPFWICevMx+SL5+bIjG4yw3A9ieYKKwf2wTEvK0gMRYOln9+KmbNRB3FRbVQBLuCEWIHT0V9GxATT9VeJ+HT88vh/B/6dj7CbWBdWbZ4QXzo0q+uyGchopl"
primary_address = "/ip4/127.0.0.1/udp/28000"
network_key = "Bh4HY09Du+3UqAlVXTk9oyJaIj0o3JPA/0scTCwaEWc="
worker_address = "/ip4/127.0.0.1/udp/28101/http"
worker_public_key = "Bh4HY09Du+3UqAlVXTk9oyJaIj0o3JPA/0scTCwaEWc="
worker_mempool = "/ip4/127.0.0.1/tcp/28102/http"

[[committee]]
owner = "AzKhol9Ut1NsdXYzIqrYd9YuzCAGShiYgNgkeTkR8qOX"
primary_public_key = "mAT9YIKvBhmi8L3e50/pr/dna1EaYELYTBuTwWgc7qoj5GrJ86/+7aX2mubVYOMxCUr2CO4H5nCgBBssNJ2u/buAPeM4MmEl+wmPgrX0uAAMzHyUOYQKVHCBFeFWsHJR"
primary_address = "/ip4/127.0.0.1/udp/38000"
network_key = "b87GFUI1X6OSU4pDDHkx3bIPVDAedUWU3UDU07oeDO0="
worker_address = "/ip4/127.0.0.1/udp/38101/http"
worker_public_key = "b87GFUI1X6OSU4pDDHkx3bIPVDAedUWU3UDU07oeDO0="
worker_mempool = "/ip4/127.0.0.1/tcp/38102/http"

[[committee]]
owner = "AhlKp53o4Jn3BzfUeFndv/84smRH5tmEmntxoqZhqey9"
primary_public_key = "tgLk6pAP2M9GrlrZnB9Y2zOCSbtAhc+bVXtnkX2oBZa0iH5JNPhyQWO0YhAHCisjCMbGSQEm8D2q/4THiCQOmXOXETHQ5Mb1SJQ5PvIRaavZ/UZm5KVYOfj2Zg415aUa"
primary_address = "/ip4/127.0.0.1/udp/8000"
network_key = "FzAP+CZcG2HTzYHaGzGsamJDpw1nq0CRnmzl5SgUqmE="
worker_address = "/ip4/127.0.0.1/udp/8101/http"
worker_public_key = "FzAP+CZcG2HTzYHaGzGsamJDpw1nq0CRnmzl5SgUqmE="
worker_mempool = "/ip4/127.0.0.1/tcp/8102/http"

[[service]]
id = 0
owner = "AuFr10sT3ObVRNoTuvJbh0ncSJS6o18oWCFmyXKirdKF"
commodity_type = "Bandwidth"

[[service]]
id = 1
owner = "A2wabLjqOtlgI8XlpTtq5ieDfyA04afQdyq4a7NQFXZB"
commodity_type = "Compute"


[[account]]
public_key = "AtQVhl1ZlXlEF4Kd3rMFlRkXBd5T0dxumfdSheh3v2eY"
flk_balance = 100
stables_balance = 100
bandwidth_balance = 100

[[commodity_prices]]
commodity = "Bandwidth"
price = 0.1

[[commodity_prices]]
commodity = "Compute"
price = 0.2

[rep_scores]

[node_info]

[total_served]

[current_epoch_served]

[[latencies]]
node_public_key_lhs = "l0Jel6KEFG7H6sV2nWKOQxDaMKWMeiUBqK5VHKcStWrLPHAANRB+dt7gp0jQ7ooxEaI7ukOQZk6U5vcL7ESHA1J/iAWQ7YNO/ZCvR1pfWfcTNBONIzeiUWAN+iyKfV10"
node_public_key_rhs = "qipezx5pzmPFWICevMx+SL5+bIjG4yw3A9ieYKKwf2wTEvK0gMRYOln9+KmbNRB3FRbVQBLuCEWIHT0V9GxATT9VeJ+HT88vh/B/6dj7CbWBdWbZ4QXzo0q+uyGchopl"
latency_in_microseconds = 100000

[[latencies]]
node_public_key_lhs = "mAT9YIKvBhmi8L3e50/pr/dna1EaYELYTBuTwWgc7qoj5GrJ86/+7aX2mubVYOMxCUr2CO4H5nCgBBssNJ2u/buAPeM4MmEl+wmPgrX0uAAMzHyUOYQKVHCBFeFWsHJR"
node_public_key_rhs = "qipezx5pzmPFWICevMx+SL5+bIjG4yw3A9ieYKKwf2wTEvK0gMRYOln9+KmbNRB3FRbVQBLuCEWIHT0V9GxATT9VeJ+HT88vh/B/6dj7CbWBdWbZ4QXzo0q+uyGchopl"
latency_in_microseconds = 200000

