[package]
name = "example-machine-comprehension"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
cdk-rust = { path = "../../../../../lib/cdk-rust" }
serde_json = "1.0"
ndarray = "0.15"
rand = "0.8"
reqwest = "0.11"
safetensors = "0.4"
safetensors-ndarray = { path = "../../../../../lib/safetensors-ndarray" }
tokenizers = { version = "0.15", default-features = false, features = [ "onig", "http" ] }
tokio.workspace = true
workspace-hack = { version = "0.1", path = "../../../../../etc/workspace-hack" }
