[package]
name = "draco-test-utils"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
draco-interfaces = {path="../interfaces"}
draco-application = {path="../application"}
async-trait.workspace = true
fleek-crypto.workspace = true
affair.workspace = true
anyhow.workspace = true
rand.workspace = true
serde.workspace = true
tokio.workspace = true
scc.workspace = true
hp-float.workspace = true

