name: Lints

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cargo Format
        run: cargo fmt --check

  clippy:
    name: Clippy
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "lints"
      - name: Cargo Clippy 
        run: cargo clippy --all-features --all-targets -- -Dclippy::all

  check:
    name: Check
    needs: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "lints"
          save-if: "false"
      - name: Cargo Check
        run: cargo check --all 
