name: Commits

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cargo Format
        run: cargo fmt --check

  clippy:
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "draco"
      - name: Cargo Clippy 
        run: cargo clippy --all-features --all-targets -- -Dclippy::all

  check:
    needs: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "draco"
          save-if: "false"
      - name: Cargo Check
        run: cargo check --all 
