name: Lints

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cargo Format
        run: cargo fmt --check

  clippy:
    name: Clippy
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rust Cache
        # Enable caching of the 'librocksdb-sys' crate by additionally caching the
        # 'librocksdb-sys' src directory which is managed by cargo
        uses: bmwill/rust-cache@v1 # Fork of 'Swatinem/rust-cache' which allows caching additional paths
        with:
          path: ~/.cargo/registry/src/**/librocksdb-sys-*
          shared-key: "lints"
      - name: Cargo Clippy 
        run: cargo clippy --all-features --all-targets -- -Dclippy::all

  check:
    name: Check
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rust Cache
        # Enable caching of the 'librocksdb-sys' crate by additionally caching the
        # 'librocksdb-sys' src directory which is managed by cargo
        uses: bmwill/rust-cache@v1 # Fork of 'Swatinem/rust-cache' which allows caching additional paths
        with:
          path: ~/.cargo/registry/src/**/librocksdb-sys-*
          shared-key: "lints"
          save-if: "false"
      - name: Cargo Check
        run: cargo check --all 
