name: Rust

on:
  schedule:
    # Trigger the CI from 7am-7pm EST every 2 hours.
    #
    # 11:00 UTC = 07:00 EST
    # 23:00 UTC = 19:00 EST
    #
    # but we separate the first run of the day because that needs to be
    # executed if there is any change in the last 12 hours and not 2.
    - cron: '0 11 * * *'
    - cron: '0 13,15,17,19,21,23 * * *'
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required to count the commits

    # Count the number of commits in the last 2 hours.
    - name: Get new commits (2h)
      if: github.event.schedule != '0 11 * * *'
      run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '2 hours ago' | wc -l)" >> $GITHUB_ENV

    # Count the number of commits in the last 12 hours.
    - name: Get new commits (12h)
      if: github.event.schedule == '0 11 * * *'
      run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '12 hours ago' | wc -l)" >> $GITHUB_ENV

    - name: Log skipped CI.
      if: env.NEW_COMMIT_COUNT == 0
      run: echo "Exiting the CI since there has not been any new commits."

    # <------------------------------------------------
    # Run the following tasks on every commit, this part of the CI takes about 2min and
    # is not a bad idea to run it for each commit.
    #
    # But since the CI is also triggered every 2 hours, skip every step if there hasn't
    # been any new commits to the repository in that span.

    - name: Format
      if: env.NEW_COMMIT_COUNT > 0
      run: cargo fmt --check

    - name: Clippy
      if: env.NEW_COMMIT_COUNT > 0
      run: cargo clippy --all-features --all-targets

    - name: Check
      if: env.NEW_COMMIT_COUNT > 0
      run: cargo +stable check --all

    # ------------------------------------------------>
    # For the following tasks, only run them if:
    # 1. The code has changed in the last 2 hours.
    # 2. If the action is triggered by the cron scheduler.

    - name: Build Release
      if: >-
        github.event.schedule != '' &&
        env.NEW_COMMIT_COUNT > 0
      run: cargo +stable build --all --release

    - name: Test
      if: >-
        github.event.schedule != '' &&
        env.NEW_COMMIT_COUNT > 0
      run: cargo +stable test --all
