[package]
name = "fleek-service-ai"
version = "0.0.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.21"
bytes.workspace = true
derive_more = "0.99"
fn-sdk = { path = "../../lib/sdk" }
hex = "0.4"
serde.workspace = true
serde_json.workspace = true
tch = { version = "0.15", features = ["download-libtorch"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
tokio.workspace = true

[[bin]]
name = "fn-service-2"
path = "src/bin.rs"
