[package]
name = "fleek-service-ai"
version = "0.0.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
bincode.workspace = true
borsh = { version = "1.3"}
rmp-serde = "1.1"
bytes = { version = "1.5", features = ["serde"] }
derive_more = "0.99"
fn-sdk = { path = "../../lib/sdk" }
hex = "0.4"
ndarray = "0.15"
ndarray-npy = "0.8"
npyz = "0.8"
ort = { version = "2.0.0-rc.0", features = ["custom-ops"] }
serde.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
tokio.workspace = true
url ="2.5.0"

[[bin]]
name = "fn-service-2"
path = "src/bin.rs"
