[package]
name = "fleek-service-ai"
version = "0.0.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.21"
bytes = { version = "1.5", features = ["serde"] }
derive_more = "0.99"
fn-sdk = { path = "../../lib/sdk" }
hex = "0.4"
ndarray = "0.15"
ndarray-npy = "0.8"
npyz = "0.8"
ort = "2.0.0-alpha.4"
serde.workspace = true
serde_json.workspace = true
tch = { version = "0.15", features = [ "download-libtorch" ]}
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
tokio.workspace = true
url ="2.5.0"

[dev-dependencies]
reqwest = "0.11"
image = "0.24"
tch = { version = "0.15", features = [ "download-libtorch" ] }

[[bin]]
name = "fn-service-2"
path = "src/bin.rs"
